language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U inquirer
  - pip install -U codecov
  - pip install -U coverage
# command to run tests
script:
  - coverage run -m pytest -v tests/test.py
after_success:
  - bash <(curl -s https://codecov.io/bash) -c -F pytests
